[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "搜索"
  pageRef = "search"
  weight = 40

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 50
