colorScheme = "violet"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = ["posts"]
disableImageOptimization = false

[homepage]
  layout = "profile"
  homepageImage = ""
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  sharingLinks = ["twitter", "reddit", "telegram"]

[list]
  showBreadcrumbs = true
  showTableOfContents = false
  groupByYear = true
  cardView = true

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false

[taxonomy]
  showTermCount = true
  cardView = true
